INSERT INTO permissions (display_name, module_name, type, created_at, updated_at) VALUES
('Dashboard', 'App/User', 'module', NOW(), NOW()),
('Data Import', 'App/DataImport', 'module', NOW(), NOW()),
('Text Messages', 'App/TextMessage', 'module', NOW(), NOW()),
('Company Information', 'App/CompanyInformation', 'module', NOW(), NOW()),
('Company Preferences', 'App/CompanyPreference', 'module', NOW(), NOW()),
('Payment Gateway Settings', 'App/PaymentGatewaySetting', 'module', NOW(), NOW()),
('Estimate & Job Statuses', 'App/Estimate&JobStatuse', 'module', NOW(), NOW()),
('Service Contract Terms', 'App/ServiceContractTerm', 'module', NOW(), NOW()),
('Communication Templates', 'App/CommunicationTemplate', 'module', NOW(), NOW()),
('Outbound Email Settings', 'App/OutboundEmailSetting', 'module', NOW(), NOW()),
('Electronic Fax Settings', 'App/ElectronicFaxSetting', 'module', NOW(), NOW()),
('Online & App Booking Settings', 'App/Online&AppBookingSetting', 'module', NOW(), NOW()),
('Referral Sources', 'App/ReferralSource', 'module', NOW(), NOW()),
('Workforce Management', 'App/WorkforceManagement', 'module', NOW(), NOW()),
('Service Agreement Management', 'App/ServiceAgreementManagement', 'module', NOW(), NOW()),
('Integrations', 'App/Integration', 'module', NOW(), NOW()),
('Crew Management', 'App/CrewManagement', 'module', NOW(), NOW()),
('Fleet Management', 'App/FleetManagement', 'module', NOW(), NOW()),
('Vendor Management', 'App/VendorManagement', 'module', NOW(), NOW()),
('Inventory Management', 'App/InventoryManagement', 'module', NOW(), NOW()),
('Product Catalog', 'App/ProductCatalog', 'module', NOW(), NOW()),
('Purchase Orders Management', 'App/PurchaseOrdersManagement', 'module', NOW(), NOW()),
('Service Catalog', 'App/ServiceCatalog', 'module', NOW(), NOW()),
('Taxes, Fees & Discounts', 'App/Taxes,Fees&Discount', 'module', NOW(), NOW()),
('Job Categories', 'App/JobCategorie', 'module', NOW(), NOW()),
('Company Memos', 'App/CompanyMemo', 'module', NOW(), NOW()),
('Notification Templates', 'App/NotificationTemplate', 'module', NOW(), NOW()),
('Customers', 'App/User', 'module', NOW(), NOW()),
('Projects', 'App/Project', 'module', NOW(), NOW()),
('Grid', 'App/User', 'module', NOW(), NOW()),
('Dispatch Zones', 'App/DispatchZone', 'module', NOW(), NOW()),
('Fleet Tracking', 'App/FleetTracking', 'module', NOW(), NOW()),
('Calendar', 'App/User', 'module', NOW(), NOW()),
('Invoices', 'App/Invoice', 'module', NOW(), NOW()),
('Invoice Payments', 'App/InvoicePayment', 'module', NOW(), NOW()),
('Sales Revenue', 'App/SalesRevenue', 'module', NOW(), NOW()),
('Sales Commission', 'App/SalesCommission', 'module', NOW(), NOW()),
('Payroll', 'App/Payroll', 'module', NOW(), NOW()),
('Jobs', 'App/Job', 'module', NOW(), NOW()),
('Estimates', 'App/Estimate', 'module', NOW(), NOW());